var searchData=
[
  ['r',['R',['../classandroid_1_1support_1_1graphics_1_1drawable_1_1_r.html',1,'android::support::graphics::drawable']]],
  ['r',['R',['../classandroid_1_1support_1_1fragment_1_1_r.html',1,'android::support::fragment']]],
  ['r',['R',['../classandroid_1_1support_1_1v7_1_1cardview_1_1_r.html',1,'android::support::v7::cardview']]],
  ['r',['R',['../classandroid_1_1support_1_1v7_1_1recyclerview_1_1_r.html',1,'android::support::v7::recyclerview']]],
  ['r',['R',['../classandroid_1_1support_1_1design_1_1_r.html',1,'android::support::design']]],
  ['r',['R',['../classandroid_1_1support_1_1graphics_1_1drawable_1_1animated_1_1_r.html',1,'android::support::graphics::drawable::animated']]],
  ['r',['R',['../classcom_1_1companyname_1_1contactos_1_1_r.html',1,'com::companyname::contactos']]],
  ['r',['R',['../classandroid_1_1support_1_1mediacompat_1_1_r.html',1,'android::support::mediacompat']]],
  ['r',['R',['../classandroid_1_1support_1_1v7_1_1appcompat_1_1_r.html',1,'android::support::v7::appcompat']]],
  ['r',['R',['../classandroid_1_1support_1_1compat_1_1_r.html',1,'android::support::compat']]],
  ['r',['R',['../classandroid_1_1support_1_1coreui_1_1_r.html',1,'android::support::coreui']]],
  ['r',['R',['../classandroid_1_1support_1_1coreutils_1_1_r.html',1,'android::support::coreutils']]],
  ['r',['R',['../classandroid_1_1support_1_1v7_1_1mediarouter_1_1_r.html',1,'android::support::v7::mediarouter']]],
  ['r',['R',['../classandroid_1_1support_1_1v4_1_1_r.html',1,'android::support::v4']]],
  ['recyclerview_5fitemanimator_5fitemanimatorfinishedlistenerimplementor',['RecyclerView_ItemAnimator_ItemAnimatorFinishedListenerImplementor',['../classmono_1_1android_1_1support_1_1v7_1_1widget_1_1_recycler_view___item_animator___item_animator_finished_listener_implementor.html',1,'mono::android::support::v7::widget']]],
  ['recyclerview_5fonchildattachstatechangelistenerimplementor',['RecyclerView_OnChildAttachStateChangeListenerImplementor',['../classmono_1_1android_1_1support_1_1v7_1_1widget_1_1_recycler_view___on_child_attach_state_change_listener_implementor.html',1,'mono::android::support::v7::widget']]],
  ['recyclerview_5fonitemtouchlistenerimplementor',['RecyclerView_OnItemTouchListenerImplementor',['../classmono_1_1android_1_1support_1_1v7_1_1widget_1_1_recycler_view___on_item_touch_listener_implementor.html',1,'mono::android::support::v7::widget']]],
  ['recyclerview_5frecyclerlistenerimplementor',['RecyclerView_RecyclerListenerImplementor',['../classmono_1_1android_1_1support_1_1v7_1_1widget_1_1_recycler_view___recycler_listener_implementor.html',1,'mono::android::support::v7::widget']]],
  ['remoteplaybackclient_5fonmessagereceivedlistenerimplementor',['RemotePlaybackClient_OnMessageReceivedListenerImplementor',['../classmono_1_1android_1_1support_1_1v7_1_1media_1_1_remote_playback_client___on_message_received_listener_implementor.html',1,'mono::android::support::v7::media']]],
  ['resource',['Resource',['../class_contactos_1_1_droid_1_1_resource.html',1,'Contactos::Droid']]]
];
